# Generated by Django 4.1.7 on 2023-07-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'الكورسات',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=255, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('city', models.CharField(max_length=255, verbose_name='المدينة')),
                ('zip_code', models.CharField(max_length=10, verbose_name='الكود')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('major', models.CharField(max_length=255, verbose_name='الأساسي')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='التقدير')),
                ('graduation_date', models.DateField(verbose_name='تاريخ التخرج')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10, verbose_name='الفصل الدراسي')),
                ('grade', models.CharField(max_length=2, verbose_name='الدرجة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.course', verbose_name='الكورس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.faculty', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.faculty', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='university_app.course', verbose_name='المتطلبات'),
        ),
    ]
