# Generated by Django 4.1.7 on 2023-07-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0002_rename_department_department_faculty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'كلية', 'verbose_name_plural': 'الكليات'},
        ),
    ]
